### PR TITLE
Update vagrantfile

### PR DESCRIPTION
**Pull request by JasonGiedymin**
Updates vagrantfile with more distros, and common ci script. All efforts are made to duplicate travisci in test operation.

### CODE REVIEW

**Comment by JasonGiedymin** [comment]
Reviewers welcome.

**Comment by ninthnails** [comment]
This is a clever way of running the playbook. Unfortunately I got this error when trying it on my Mac:
```
$ vagrant up travis
Bringing machine 'travis' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

**Comment by JasonGiedymin** [comment]
Whoops. Need to document the probable need for guest plugin if one desires nfs.

I'll take a look tonight and see if I can tie it to the nfs param as well.

Try this: `vagrant plugin install vagrant-vbguest`

**Comment by ninthnails** [comment]
Okay installed the plugin and tested again. Works but took forever to complete ;)

**Pull request merged**
